### ISSUE TITLE
NoMethodError: undefined method `find_or_create_by_email'

### ISSUE THREAD

**Issue by n4rk0o** [ajf8/mcomaster#37]
Hello,

I try to install 'mcomaster' but I have an issue during it.

I try to install on a CentOS 7 and after the command : RAILS_ENV=production scl enable ruby193 "bundle exec bin/rake db:reset --trace"

*\* Invoke db:reset (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Invoke db:load_config (first_time)
*\* Execute db:load_config
*\* Execute db:reset
*\* Invoke db:drop (first_time)
*\* Invoke db:load_config
*\* Execute db:drop
*\* Invoke db:setup (first_time)
*\* Invoke db:schema:load_if_ruby (first_time)
*\* Invoke db:create (first_time)
*\* Invoke db:load_config
*\* Execute db:create
*\* Invoke environment
*\* Execute db:schema:load_if_ruby
*\* Invoke db:schema:load (first_time)
*\* Invoke environment
*\* Invoke db:load_config
*\* Execute db:schema:load
-- create_table("actlogs", {:force=>true})
   -> 0.1185s
-- create_table("app_settings", {:force=>true})
   -> 0.0039s
-- create_table("filter_members", {:force=>true})
   -> 0.0047s
-- create_table("filters", {:force=>true})
   -> 0.0041s
-- create_table("policies", {:force=>true})
   -> 0.0038s
-- create_table("policy_defaults", {:force=>true})
   -> 0.0038s
-- create_table("reply_items", {:force=>true})
   -> 0.0043s
-- create_table("responselogs", {:force=>true})
   -> 0.0039s
-- create_table("roles", {:force=>true})
   -> 0.0058s
-- add_index("roles", ["name", "resource_type", "resource_id"], {:name=>"index_roles_on_name_and_resource_type_and_resource_id"})
   -> 0.0048s
-- add_index("roles", ["name"], {:name=>"index_roles_on_name"})
   -> 0.0042s
-- create_table("users", {:force=>true})
   -> 0.0131s
-- add_index("users", ["email"], {:name=>"index_users_on_email", :unique=>true})
   -> 0.0048s
-- add_index("users", ["reset_password_token"], {:name=>"index_users_on_reset_password_token", :unique=>true})
   -> 0.0047s
-- create_table("users_roles", {:id=>false, :force=>true})
   -> 0.0040s
-- add_index("users_roles", ["user_id", "role_id"], {:name=>"index_users_roles_on_user_id_and_role_id"})
   -> 0.0049s
-- initialize_schema_migrations_table()
   -> 0.0056s
*\* Invoke db:structure:load_if_sql (first_time)
*\* Invoke db:create
*\* Invoke environment
*\* Execute db:structure:load_if_sql
*\* Invoke db:seed (first_time)
*\* Execute db:seed
*\* Invoke db:abort_if_pending_migrations (first_time)
*\* Invoke environment
*\* Execute db:abort_if_pending_migrations
ROLES
role: admin
role: user
role: VIP
DEFAULT USERS
rake aborted!
NoMethodError: undefined method `find_or_create_by_email' for #<Class:0x00000005ca2f88>
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.4/lib/active_record/dynamic_matchers.rb:26:in`method_missing'
/usr/share/mcomaster/db/seeds.rb:18:in `<top (required)>'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in`load'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `block in load'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in`load_dependency'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/railties-4.1.4/lib/rails/engine.rb:543:in`load_seed'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.4/lib/active_record/tasks/database_tasks.rb:184:in `load_seed'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.4/lib/active_record/railties/databases.rake:173:in`block (2 levels) in <top (required)>'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in`block in execute'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in`execute'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/rh/ruby193/root/usr/share/ruby/monitor.rb:211:in`mon_synchronize'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:201:in`block in invoke_prerequisites'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:199:in`invoke_prerequisites'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/opt/rh/ruby193/root/usr/share/ruby/monitor.rb:211:in`mon_synchronize'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:165:in`invoke'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.4/lib/active_record/railties/databases.rake:132:in `block (2 levels) in <top (required)>'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in`call'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in`each'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:179:in`block in invoke_with_call_chain'
/opt/rh/ruby193/root/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in`invoke_with_call_chain'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:150:in`invoke_task'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in`each'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:115:in`run_with_threads'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:78:in`block in run'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/share/mcomaster/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:75:in`run'
bin/rake:4:in `<main>'
Tasks: TOP => db:setup => db:seed

I don't know why this occurs...

Thank you :)

**Comment by n4rk0o** [comment]
After reinstall the package the issue is solved.
